INSERT INTO `#__fields_groups` (
	`asset_id`, 
	`context`, 
	`title`, 
	`note`, 
	`description`, 
	`state`, 
	`checked_out`, 
	`checked_out_time`, 
	`ordering`, 
	`params`, 
	`language`, 
	`created`, 
	`created_by`, 
	`modified`, 
	`modified_by`, 
	`access`) 
VALUES (
	9998, 
	'com_content.article', 
	'Business Info', 
	'', 
	'', 
	1, 
	0, 
	'0000-00-00 00:00:00', 
	0, 
	'{"display_readonly":"1"}', 
	'*', 
	CURRENT_TIMESTAMP, 
	0, 
	'0000-00-00 00:00:00', 
	0, 
	1) ON DUPLICATE KEY UPDATE `asset_id` = 9998, `title` = 'Business Info';

SET @group_id = (SELECT `id` FROM `#__fields_groups` WHERE `title` = 'Business Info');

INSERT INTO `#__fields` (
	`asset_id`, 
	`context`, 
	`title`, 
	`group_id`, 
	`name`, 
	`label`, 
	`default_value`, 
	`type`, 
	`note`, 
	`description`, 
	`state`, 
	`required`, 
	`checked_out`, 
	`checked_out_time`, 
	`ordering`, 
	`params`, 
	`fieldparams`, 
	`language`, 
	`created_time`, 
	`created_user_id`, 
	`modified_time`, 
	`modified_by`, 
	`access`) 
VALUES (
	9998, 
	'com_content.article',
	'Информация о работе',
	@group_id, 
	'business-info', 
	'Информация о работе', 
	'', 
	'repeatable', 
	'', 
	'', 
	1, 
	0, 
	0, 
	CURRENT_TIMESTAMP, 
	0, 
	'{"hint":"","class":"","label_class":"","show_on":"","render_class":"","showlabel":"1","label_render_class":"","display":"0","layout":"","display_readonly":"2"}',
	'{"fields":{"fields0":{"fieldname":"Название организации","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields1":{"fieldname":"Адрес отделения (через запятую в формате адрес с номером дома, город, область, почтовый код)","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields2":{"fieldname":"Логотип","fieldtype":"media","fieldfilter":"0"},"fields3":{"fieldname":"Контактный телефон","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields4":{"fieldname":"Адрес электронной почты","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields5":{"fieldname":"Сайт в интернете","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields6":{"fieldname":"Рабочие дни (полные названия через запятую)","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields7":{"fieldname":"Рабочие дни (сокращенные названия через запятую)","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields8":{"fieldname":"Рабочее время (через дефис в 24-часовом формате)","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields9":{"fieldname":"Способы оплаты услуг","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"},"fields10":{"fieldname":"Ценовой диапазон","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"}, "fields11":{"fieldname":"Специализация","fieldtype":"text","fieldfilter":"JComponentHelper::filterText"}}}',
	'*',
	CURRENT_TIMESTAMP,
	0,
	CURRENT_TIMESTAMP,
	0,
	1) ON DUPLICATE KEY UPDATE `asset_id` = 9998, `title` = 'Информация о работе отделений';